# Generated by Django 4.2.6 on 2023-11-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockADS', '0003_alter_categories_options_alter_products_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
