# Generated by Django 4.2.4 on 2023-11-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='activo',
            new_name='in_stock',
        ),
        migrations.AddField(
            model_name='user',
            name='cod',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='senha',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='usuario',
            field=models.CharField(max_length=100),
        ),
    ]
