# Generated by Django 4.2.6 on 2023-11-09 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_activo_user_in_stock_user_cod_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
